version: 2

updates:
    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: "weekly"
        assignees:
            - "jubianchi"
        versioning-strategy: "lockfile-only"
        pull-request-branch-name:
            separator: "-"
